import { writeFile } from 'node:fs/promises';
import { Header, Footer } from '../src/components.mjs';
import { Hero, Introduction, SelectedProjects, Philosophy, CredibilitySection, CTASection } from '../src/homepage.mjs';

const html = `<!doctype html>
<!-- Generated by node scripts/build.mjs. Edit src/ modules, then regenerate. -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>WeR1 Infra | Real Estate &amp; Construction</title>
  <meta name="description" content="Founded in 2022, WeR1 Infra delivers residential and commercial construction and real estate projects. Explore our completed, ongoing and upcoming developments.">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="WeR1 Infra">
  <meta property="og:title" content="WeR1 Infra | Real Estate &amp; Construction">
  <meta property="og:description" content="Discover WeR1 Infra's approach to real-estate development, architecture and construction.">
  <meta property="og:url" content="https://wer1group.in/">
  <link rel="canonical" href="https://wer1group.in/">
  <link rel="icon" href="data:,">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;1,300&amp;family=Inter:wght@400;500;600&amp;display=swap" rel="stylesheet">
  <link rel="stylesheet" href="style.css">
  <script src="assets/navigation.js" defer></script>
</head>
<body id="home">
  <a class="skip-link" href="#main-content">Skip to content</a>
  ${Header()}
  <main id="main-content" tabindex="-1">${Hero()}${Introduction()}${SelectedProjects()}${Philosophy()}${CredibilitySection()}${CTASection()}</main>
  ${Footer()}
</body>
</html>
`;

await writeFile(new URL('../index.html', import.meta.url), html);
console.log('Built index.html. Static hosting and deployment root are unchanged.');
